export { lazyAsync } from './async'
export type { LazyAsyncFn, LazyAsyncOptions } from './async'
export { block } from './block'
export type { Block } from './block'
export { lazyFn } from './fn'
export type { LazyFn, LazyFnOptions } from './fn'
export { lazyObj, lazyObjCached } from './obj'
export type { LazyObj } from './obj'
