export { lazyAsync } from './async'
export type { LazyAsyncFn, LazyAsyncOptions } from './async'
export { lazyFn } from './fn'
export type { LazyFn, LazyFnOptions } from './fn'
export { lazyObj, lazyObjCached } from './obj'
export type { LazyObj, LazyOptions } from './obj'
