[package]
authors = ["Reiss Davidson <https://github.com/reiss-d>"]
description = "SWC plugin for lazily initalizing variables."
edition = "2021"
license = "MIT"
name = "swc_plugin_lazy_init"
publish = false
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
use-swc_core_v069 = ["swc_core_v069"]
# v066_68 dropped due to https://github.com/swc-project/swc/issues/7053
# use-swc_core_v066_68 = ["swc_core_v066_68"]
use-swc_core_v061_64 = ["swc_core_v061_64"]
use-swc_core_v054_59 = ["swc_core_v054_59"]

use-testing = [
  "swc_core_v069?/ecma_parser",
  "swc_core_v069?/ecma_transforms",
  "swc_core_v069?/testing_transform",
  #
  "swc_core_v061_64?/ecma_parser",
  "swc_core_v061_64?/ecma_transforms",
  "swc_core_v061_64?/testing_transform",
  #
  "swc_core_v054_59?/ecma_parser",
  "swc_core_v054_59?/ecma_transforms",
  "swc_core_v054_59?/testing_transform",
  #
  "testing",
]
use-plugin_transform = [
  "swc_core_v069?/ecma_plugin_transform",
  "swc_core_v061_64?/ecma_plugin_transform",
  "swc_core_v054_59?/ecma_plugin_transform",
  "rand",
]

[dependencies]
rand = { version = "0.8.5", optional = true }
swc_core_v069 = { package = "swc_core", version = "0.69.0", optional = true, features = [
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",
] }
swc_core_v061_64 = { package = "swc_core", version = "0.64.10", optional = true, features = [
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",
] }
swc_core_v054_59 = { package = "swc_core", version = "0.59.40", optional = true, features = [
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",
] }

serde_json = "1"
serde = { version = "1.0.152", features = ["derive"] }
tracing = { version = "0.1.37", features = ["release_max_level_off"] }
testing = { version = "0.31.20", optional = true }
